### ISSUE TITLE
SQL Import Error

### ISSUE THREAD

**Issue by hostlinkau** [hsdn/pwhoisd#1]
Hi

When using your software here, we have attempted to import the sql file but are given the following error

ERROR 1293 (HY000) at line 120: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

Can you please help resolve this?

Daniel

**Comment by justkeepquiet** [comment]
Hello. 

Please replace the line 133 in "example_pwhoisd.sql" to:
` created timestamp NOT NULL DEFAULT 0,`

Fixed now. Thanks.

**Comment by hostlinkau** [comment]
Hey mate

Fixed that. but now when running the test. it hangs

[root@lg ~]# whois -h 127.0.0.1 "hsdn.ru"
[Querying 127.0.0.1]


nothing is returned?
