### ISSUE TITLE
Whois information not found

### ISSUE THREAD

**Issue by chathurag** [hsdn/pwhoisd#3]
whois -h 119.235.0.110 "119.235.0.4"
[Querying 119.235.0.110]
[119.235.0.110]
% By submitting a query to RIPN's Whois Service
% you agree to abide by the following terms of use:
% http://www.ripn.net/about/servpol.html#3.2 (in Russian)
% http://www.ripn.net/about/en/servpol.html#3.2 (in English).

No entries found for the selected source(s).

Last updated on 2015.04.20 07:31:51 MSK

Unable to get information for whois?

Is there any way to sync mysql database automatically.

**Comment by justkeepquiet** [comment]
The server provides only local whois service, for your own local database (for example, if you have your own TLD or other resources). Synchronization with other whois databases is not provided.
